#!/usr/bin/env node
var shell = require('shelljs')
var path = require('path')

var environment = require('./environment.json')
var runScript = path.join(__dirname, 'run.js')

var command = (environment['executable-path'] + ' ' +
              environment['executable-options'].join(' ') + ' ' +
              runScript + ' ' +
              process.argv.slice(2).join(' '))

if (shell.exec(command).code !== 0) {
  shell.exit(1)
} else {
  shell.exit(0)
}


